create table if not exists categories
(
    cat_id   bigint generated by default as identity not null,
    cat_name varchar(200)                            not null,
    constraint pk_cat primary key (cat_id),
    constraint uq_name_cat unique (cat_name)
);

create table if not exists users
(
    user_id  bigint generated by default as identity not null,
    email    varchar(50)                             not null,
    username varchar(100)                            not null,
    constraint pk_u primary key (user_id),
    constraint uq_email unique (email)
);

create table if not exists events
(
    event_id bigint generated by default as identity not null ,
    annotation varchar(200) not null ,
    cat_id bigint not null ,

)

create table if not exists requests
(
    req_id      bigint generated by default as identity not null,
    req_created varchar(100)                            not null,
    event_id    bigint                                  not null,
    user_id     bigint                                  not null,
    constraint pk_req primary key (req_id),
    constraint fk_req_event foreign key (event_id) references events (event_id),
    constraint fk_req_user foreign key (user_id) references users (user_id)
);
