drop table if exists applications cascade;
drop table if exists stats cascade;

create table if not exists applications
(
    app_id bigint generated by default as identity not null,
    app    varchar(20),
    constraint pk_app primary key (app_id),
    constraint uq_app unique (app)
);

create table if not exists stats
(
    stats_id  bigint generated by default as identity not null,
    app_id    bigint,
    uri       varchar(256)                            not null,
    ip        varchar(15)                             not null,
    timestamp varchar(100)                            not null,
    constraint pk_stat primary key (stats_id),
    constraint fk_app foreign key (app_id) references applications (app_id)
);
