drop table if exists stats;
create table if not exists stats
(
    id_stats  bigint generated by default as identity not null,
    app       varchar(100)                            not null,
    uri       varchar(256)                            not null,
    ip        varchar(15)                             not null,
    timestamp varchar(100)                            not null,
    constraint pk_stat primary key (id_stats)
)